import { router } from "expo-router";
import { useState } from "react";
import { StyleSheet, Text, View } from "react-native";

import { Button, Card, Screen, ScreenHeader } from "@/src/components/ui";
import { useLocale } from "@/src/lib/i18n";
import { registerForPushNotifications, unregisterPushDevice } from "@/src/lib/push";
import { useMobileAccount } from "@/src/providers/MobileAccountProvider";
import { colors, spacing, typography } from "@/src/theme/tokens";

export default function SettingsScreen() {
  const { language, setLanguage, pick } = useLocale(); const { state, user, workspaceError, logout } = useMobileAccount();
  const [pushState, setPushState] = useState<"idle" | "busy" | "enabled">("idle"); const [message, setMessage] = useState<string | null>(null);
  async function enablePush() { setPushState("busy"); setMessage(null); try { await registerForPushNotifications(); setPushState("enabled"); setMessage(pick("Cet appareil recevra les alertes Anatole.", "This device will receive Anatole alerts.")); } catch (error) { setPushState("idle"); setMessage(error instanceof Error ? error.message : pick("Activation impossible.", "Unable to enable notifications.")); } }
  async function disablePush() { setPushState("busy"); try { await unregisterPushDevice(); setPushState("idle"); setMessage(pick("Notifications désactivées sur cet appareil.", "Notifications disabled on this device.")); } catch (error) { setMessage(error instanceof Error ? error.message : pick("Désactivation impossible.", "Unable to disable notifications.")); } }
  return <Screen testID="settings-screen"><ScreenHeader eyebrow={pick("Application", "Application")} title={pick("Réglages", "Settings")} subtitle={pick("Langue, compte et notifications natives.", "Language, account and native notifications.")} /><Card title={pick("Langue", "Language")}><View style={styles.buttons}><View style={{ flex: 1 }}><Button label="Français" variant={language === "fr" ? "primary" : "secondary"} onPress={() => setLanguage("fr")} /></View><View style={{ flex: 1 }}><Button label="English" variant={language === "en" ? "primary" : "secondary"} onPress={() => setLanguage("en")} /></View></View></Card><Card title={pick("Notifications push", "Push notifications")}><Text style={styles.muted}>{pick("Les permissions sont demandées seulement lorsque vous activez cette fonction. Une development build est requise sur Android.", "Permission is requested only when you enable this feature. A development build is required on Android.")}</Text>{state === "authenticated" ? <>{pushState === "enabled" ? <Button label={pick("Désactiver sur cet appareil", "Disable on this device")} variant="secondary" onPress={() => void disablePush()} /> : <Button label={pushState === "busy" ? pick("Activation…", "Enabling…") : pick("Activer sur cet appareil", "Enable on this device")} onPress={() => void enablePush()} disabled={pushState === "busy"} />}</> : <Button label={pick("Se connecter", "Sign in")} onPress={() => router.push("/(auth)/login")} />}{message ? <Text style={styles.message}>{message}</Text> : null}</Card><Card title={pick("Compte", "Account")}><Text style={styles.account}>{user?.email ?? pick("Mode découverte", "Discovery mode")}</Text>{workspaceError ? <Text style={styles.warning}>{pick("Compte actif · synchronisation temporairement indisponible", "Active account · sync temporarily unavailable")} : {workspaceError}</Text> : null}{state === "authenticated" ? <Button label={pick("Se déconnecter", "Sign out")} variant="danger" onPress={() => void logout()} /> : <Button label={pick("Se connecter", "Sign in")} onPress={() => router.push("/(auth)/login")} />}</Card><Text style={styles.legal}>{pick("Anatole fournit de l’information générale, pas des conseils de placement.", "Anatole provides general information, not investment advice.")}</Text></Screen>;
}
const styles = StyleSheet.create({ buttons: { flexDirection: "row", gap: spacing.md }, muted: { ...typography.body, color: colors.textMuted }, message: { ...typography.caption, color: colors.positive }, error: { color: colors.negative }, account: { ...typography.body, color: colors.text, fontWeight: "700" }, warning: { ...typography.caption, color: colors.warning }, legal: { ...typography.caption, color: colors.textSubtle, textAlign: "center", margin: spacing.lg } });
