import { useQuery } from "@tanstack/react-query";
import { router } from "expo-router";
import { useEffect, useState } from "react";
import { AppState, Pressable, StyleSheet, Text, View } from "react-native";
import { Card, QueryState, Screen, ScreenHeader } from "@/src/components/ui";
import { marketApi } from "@/src/lib/api/market";
import { useLocale } from "@/src/lib/i18n";
import { anatoleRoutes } from "@/src/lib/routes";
import { colors, radius, spacing, typography } from "@/src/theme/tokens";
import { discoverStrategies, screenDiscover, strategyAvailable, type DiscoverStrategy } from "./model";
const labels: Record<DiscoverStrategy, [string, string]> = { momentum: ["Momentum", "Momentum"], oversold: ["Survente", "Oversold"], unusual_volume: ["Volume inhabituel", "Unusual volume"], breakout: ["Cassure", "Breakout"], sector_leaders: ["Leaders sectoriels", "Sector leaders"], insiders: ["Activité d’initiés", "Insider activity"], value: ["Valeur", "Value"], quality: ["Qualité", "Quality"], dividend: ["Dividende", "Dividend"] };
export function DiscoverScreen() {
  const { pick } = useLocale(); const [strategy, setStrategy] = useState<DiscoverStrategy>("momentum"); const [active, setActive] = useState(AppState.currentState === "active");
  useEffect(() => { const subscription = AppState.addEventListener("change", (state) => setActive(state === "active")); return () => subscription.remove(); }, []);
  const screener = useQuery({ queryKey: ["discover-screener"], queryFn: ({ signal }) => marketApi.screener("composite", signal), enabled: active && strategy !== "insiders" && strategyAvailable(strategy), staleTime: 3 * 60_000 });
  const insiders = useQuery({ queryKey: ["discover-insiders"], queryFn: ({ signal }) => marketApi.insiders({ market: "canada", days: 90, scanLimit: 8 }, signal), enabled: active && strategy === "insiders", staleTime: 15 * 60_000 });
  const results = strategy === "insiders" ? insiders.data?.trades.filter((trade) => trade.unusual).map((trade) => ({ ticker: trade.ticker, name: trade.company, reasons: [`${trade.transaction_label} · ${trade.trade_date ?? "N/D"}`] })) ?? [] : screenDiscover(screener.data?.items ?? [], strategy);
  const available = strategyAvailable(strategy);
  return <Screen testID="discover-screen"><ScreenHeader eyebrow={pick("DÉCOUVRIR", "DISCOVER")} title={pick("Signaux explicables", "Explainable signals")} subtitle={pick("Classements descriptifs fondés sur des métriques réelles, jamais des recommandations.", "Descriptive rankings based on actual metrics, never recommendations.")} /><View style={styles.strategies}>{discoverStrategies.map((item) => <Pressable accessibilityState={{ disabled: !strategyAvailable(item), selected: strategy === item }} key={item} onPress={() => setStrategy(item)} style={[styles.chip, strategy === item && styles.active]}><Text style={styles.chipText}>{pick(...labels[item])}</Text></Pressable>)}</View>{!available ? <Card><Text style={styles.unavailable}>{pick("Données insuffisantes actuellement. Aucun batch fiable n’est disponible pour cette stratégie.", "Insufficient data currently. No reliable batch is available for this strategy.")}</Text></Card> : null}<QueryState error={!screener.data && strategy !== "insiders" ? screener.error : !insiders.data && strategy === "insiders" ? insiders.error : null} loading={screener.isLoading || insiders.isLoading} />{available ? <Card title={pick("Pourquoi ce titre apparaît", "Why this appears")}>{results.length ? results.map((item) => <Pressable key={`${item.ticker}-${item.reasons.join()}`} onPress={() => router.push(anatoleRoutes.focus(item.ticker))} style={styles.result}><Text style={styles.title}>{item.ticker} · {item.name}</Text>{item.reasons.map((reason) => <Text key={reason} style={styles.reason}>{reason}</Text>)}</Pressable>) : !screener.isLoading && !insiders.isLoading ? <Text style={styles.unavailable}>{pick("Aucun résultat avec les données disponibles.", "No result in the available data.")}</Text> : null}</Card> : null}</Screen>;
}
const styles = StyleSheet.create({ strategies: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs }, chip: { minHeight: 44, justifyContent: "center", paddingHorizontal: spacing.sm, borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm }, active: { borderColor: colors.primary, backgroundColor: "rgba(44,156,255,.2)" }, chipText: { ...typography.caption, color: colors.text }, unavailable: { ...typography.body, color: colors.textMuted }, result: { minHeight: 64, justifyContent: "center", borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, title: { ...typography.body, color: colors.text, fontWeight: "800" }, reason: { ...typography.caption, color: colors.primary } });
