export type InstitutionalCapabilityStage = "bridge" | "foundation" | "roadmap";

export type InstitutionalCapability = {
  id: number;
  titleFr: string;
  titleEn: string;
  summaryFr: string;
  summaryEn: string;
  area: string;
  href?: string;
  stage: InstitutionalCapabilityStage;
};

export const INSTITUTIONAL_CAPABILITIES: InstitutionalCapability[] = [
  {
    id: 1,
    titleFr: "Cockpit portefeuille institutionnel",
    titleEn: "Institutional Portfolio Cockpit",
    summaryFr: "Vue portefeuille avec P&L, expositions, risque, liquidité et drawdown.",
    summaryEn: "Portfolio view combining P&L, exposures, risk, liquidity and drawdown.",
    area: "Portfolio & Risk",
    href: "/portefeuille",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 2,
    titleFr: "Jumeau numérique du portefeuille",
    titleEn: "Portfolio Digital Twin",
    summaryFr: "Représentation vivante des positions, devises, cash, secteurs, facteurs et dépendances.",
    summaryEn: "Living representation of holdings, FX, cash, sectors, factors and dependencies.",
    area: "Portfolio & Risk",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 3,
    titleFr: "Moteur de scénarios",
    titleEn: "Scenario Engine",
    summaryFr: "Stress multi-facteurs sur taux, devises, matières premières, marchés et macro.",
    summaryEn: "Multi-factor stress scenarios across rates, FX, commodities, markets and macro.",
    area: "Portfolio & Risk",
    href: "/institutionnel/risque",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 4,
    titleFr: "Stress tests multi-actifs",
    titleEn: "Multi-Asset Stress Testing",
    summaryFr: "Stress historiques et hypothétiques sur actions, obligations, ETF, FX, options et cash.",
    summaryEn: "Historical and hypothetical stress tests across equities, bonds, ETFs, FX, options and cash.",
    area: "Portfolio & Risk",
    href: "/institutionnel/risque",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 5,
    titleFr: "Moteur d'exposition factorielle",
    titleEn: "Factor Exposure Engine",
    summaryFr: "Décompose les expositions value, growth, momentum, quality, size, taux, inflation et devises.",
    summaryEn: "Decompose value, growth, momentum, quality, size, rates, inflation and FX exposures.",
    area: "Portfolio & Risk",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 6,
    titleFr: "Portfolio X-Ray",
    titleEn: "Portfolio X-Ray",
    summaryFr: "Révèle chevauchements, expositions indirectes et concentrations économiques cachées.",
    summaryEn: "Reveal overlaps, indirect exposures and hidden economic concentration.",
    area: "Portfolio & Risk",
    href: "/portefeuille",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 7,
    titleFr: "Graphe de chaîne d'approvisionnement",
    titleEn: "Supply Chain Graph",
    summaryFr: "Relie émetteurs, fournisseurs, clients, matières premières, régions et risques.",
    summaryEn: "Connect issuers, suppliers, customers, commodities, regions and risks.",
    area: "Research & Thesis",
    href: "/focus/RY",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 8,
    titleFr: "Graphe de dépendances croisées",
    titleEn: "Cross-Portfolio Dependency Graph",
    summaryFr: "Détecte les risques communs entre titres via fournisseurs, régions, clients ou facteurs.",
    summaryEn: "Detect shared risks across holdings through suppliers, regions, customers or factors.",
    area: "Portfolio & Risk",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 9,
    titleFr: "Moteur de transmission macro",
    titleEn: "Macro Transmission Engine",
    summaryFr: "Relie taux, inflation, crédit et croissance aux secteurs puis aux positions.",
    summaryEn: "Link rates, inflation, credit and growth to sectors and portfolio holdings.",
    area: "Macro & Regimes",
    href: "/institutionnel/macro",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 10,
    titleFr: "Moteur de régimes économiques",
    titleEn: "Economic Regime Engine",
    summaryFr: "Classe les environnements de croissance, inflation, liquidité, taux et crédit.",
    summaryEn: "Classify growth, inflation, liquidity, rates and credit regimes.",
    area: "Macro & Regimes",
    href: "/institutionnel/macro",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 11,
    titleFr: "Attribution avancée",
    titleEn: "Advanced Portfolio Attribution",
    summaryFr: "Attribue la performance à la sélection, allocation, devises, facteurs et timing.",
    summaryEn: "Attribute returns to selection, allocation, FX, factors and timing.",
    area: "Portfolio & Risk",
    href: "/institutionnel/attribution",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 12,
    titleFr: "Attribution des décisions",
    titleEn: "Decision Attribution",
    summaryFr: "Compare le rationnel d'une décision à ce qui s'est réellement produit ensuite.",
    summaryEn: "Compare a decision rationale with what actually happened afterward.",
    area: "Research & Thesis",
    href: "/institutionnel/attribution",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 13,
    titleFr: "Journal d'investissement institutionnel",
    titleEn: "Institutional Investment Journal",
    summaryFr: "Conserve thèse, catalyseurs, risques, horizon, prix et conditions d'invalidation.",
    summaryEn: "Store thesis, catalysts, risks, horizon, price and invalidation conditions.",
    area: "Research & Thesis",
    href: "/institutionnel/recherche",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 14,
    titleFr: "Suivi de thèse",
    titleEn: "Thesis Monitor",
    summaryFr: "Surveille automatiquement les variables qui soutiennent chaque thèse d'investissement.",
    summaryEn: "Monitor the variables supporting each investment thesis.",
    area: "Research & Thesis",
    href: "/institutionnel/recherche",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 15,
    titleFr: "Détection de rupture de thèse",
    titleEn: "Thesis Break Detection",
    summaryFr: "Signale lorsqu'une hypothèse critique n'est plus soutenue par les données.",
    summaryEn: "Flag when a critical thesis assumption is no longer supported by data.",
    area: "Research & Thesis",
    href: "/institutionnel/recherche",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 16,
    titleFr: "Intelligence événementielle",
    titleEn: "Event Intelligence",
    summaryFr: "Relie résultats, guidance, M&A, réglementation, contrats et refinancement aux positions.",
    summaryEn: "Link earnings, guidance, M&A, regulation, contracts and refinancing to holdings.",
    area: "Research & Thesis",
    href: "/institutionnel/recherche",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 17,
    titleFr: "Centre de commande résultats",
    titleEn: "Earnings Command Center",
    summaryFr: "Prépare consensus, surprises, KPI, guidance, révisions et réaction post-résultats.",
    summaryEn: "Prepare consensus, surprises, KPIs, guidance, revisions and post-earnings reaction.",
    area: "Research & Thesis",
    href: "/institutionnel/recherche",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 18,
    titleFr: "Copilote de recherche institutionnelle",
    titleEn: "Institutional Research Copilot",
    summaryFr: "Assemble filings, résultats, comparables, macro et portefeuille avec sources traçables.",
    summaryEn: "Assemble filings, earnings, peers, macro and portfolio context with traceable sources.",
    area: "Research & Thesis",
    href: "/institutionnel/recherche",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 19,
    titleFr: "Carnet de recherche partagé",
    titleEn: "Shared Research Notebook",
    summaryFr: "Centralise notes, modèles, documents, commentaires et changements de thèse.",
    summaryEn: "Centralize notes, models, documents, comments and thesis changes.",
    area: "Research & Thesis",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 20,
    titleFr: "Traçabilité des sources",
    titleEn: "Source Lineage",
    summaryFr: "Expose source, date, fournisseur, transformation, fréquence et fraîcheur de chaque donnée.",
    summaryEn: "Expose source, date, provider, transformation, frequency and freshness for each data point.",
    area: "Data & Governance",
    href: "/institutionnel/gouvernance",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 21,
    titleFr: "Score de confiance des données",
    titleEn: "Data Confidence Score",
    summaryFr: "Mesure fraîcheur, cohérence, anomalies et données manquantes sans noter l'investissement.",
    summaryEn: "Measure freshness, consistency, anomalies and missing data without scoring the investment.",
    area: "Data & Governance",
    href: "/institutionnel/gouvernance",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 22,
    titleFr: "Intelligence du consensus",
    titleEn: "Consensus Intelligence",
    summaryFr: "Suit distribution, dispersion, révisions et divergence bull/bear des estimations.",
    summaryEn: "Track distribution, dispersion, revisions and bull/bear divergence in estimates.",
    area: "Research & Thesis",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 23,
    titleFr: "Hub de données alternatives",
    titleEn: "Alternative Data Hub",
    summaryFr: "Cadre pour données alternatives avec provenance, licences et limites explicites.",
    summaryEn: "Framework for alternative data with explicit provenance, licensing and limitations.",
    area: "Data & Governance",
    stage: "roadmap" as InstitutionalCapabilityStage,
  },
  {
    id: 24,
    titleFr: "Comparables dynamiques",
    titleEn: "Dynamic Peer Intelligence",
    summaryFr: "Construit des comparables par modèle d'affaires, croissance, marge et moteurs économiques.",
    summaryEn: "Build peers by business model, growth, margin and economic drivers.",
    area: "Research & Thesis",
    href: "/comparateur",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 25,
    titleFr: "Laboratoire de construction de portefeuille",
    titleEn: "Portfolio Construction Lab",
    summaryFr: "Teste des allocations sous contraintes de risque, liquidité, concentration et cash.",
    summaryEn: "Test allocations under risk, liquidity, concentration and cash constraints.",
    area: "Construction & Trading",
    href: "/institutionnel/construction",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 26,
    titleFr: "Laboratoire de rééquilibrage",
    titleEn: "Rebalancing Lab",
    summaryFr: "Compare plusieurs rééquilibrages par risque, turnover, coûts et expositions.",
    summaryEn: "Compare rebalancing paths by risk, turnover, costs and exposures.",
    area: "Construction & Trading",
    href: "/institutionnel/construction",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 27,
    titleFr: "Intelligence de liquidité",
    titleEn: "Liquidity Intelligence",
    summaryFr: "Suit ADV, spread, days-to-liquidate et taille de position relative au marché.",
    summaryEn: "Track ADV, spreads, days-to-liquidate and position size relative to market.",
    area: "Construction & Trading",
    href: "/terminal",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 28,
    titleFr: "Risque de crowding",
    titleEn: "Crowding Risk",
    summaryFr: "Repère concentration consensuelle, factor crowding et dépendance à des flux similaires.",
    summaryEn: "Identify consensus crowding, factor crowding and dependence on similar flows.",
    area: "Portfolio & Risk",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 29,
    titleFr: "Moniteur de régimes de corrélation",
    titleEn: "Correlation Regime Monitor",
    summaryFr: "Détecte quand les corrélations changent et réduisent la diversification attendue.",
    summaryEn: "Detect correlation changes that weaken expected diversification.",
    area: "Portfolio & Risk",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 30,
    titleFr: "Anatomie du drawdown",
    titleEn: "Drawdown Anatomy",
    summaryFr: "Explique les contributions titres, secteurs, facteurs, devises et événements à une baisse.",
    summaryEn: "Explain security, sector, factor, FX and event contributions to a drawdown.",
    area: "Portfolio & Risk",
    href: "/institutionnel/risque",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 31,
    titleFr: "Budget de risque",
    titleEn: "Risk Budgeting",
    summaryFr: "Mesure la contribution de chaque position au risque total, pas seulement son poids.",
    summaryEn: "Measure each holding's contribution to total risk, not just capital weight.",
    area: "Portfolio & Risk",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 32,
    titleFr: "Intelligence de concentration",
    titleEn: "Concentration Intelligence",
    summaryFr: "Détecte les concentrations directes et économiques indirectes d'un portefeuille.",
    summaryEn: "Detect direct and indirect economic concentration in a portfolio.",
    area: "Portfolio & Risk",
    href: "/institutionnel/risque",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 33,
    titleFr: "Alertes portefeuille intelligentes",
    titleEn: "Intelligent Portfolio Alerts",
    summaryFr: "Alerte sur changement de risque, thèse, liquidité ou dépendance plutôt que simple variation prix.",
    summaryEn: "Alert on risk, thesis, liquidity or dependency changes rather than simple price moves.",
    area: "PM Workflow",
    href: "/alertes",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 34,
    titleFr: "Institutionnel — Ce qui a changé",
    titleEn: "Institutional What Changed?",
    summaryFr: "Résumé quotidien des changements positions, risques, consensus, macro et événements.",
    summaryEn: "Daily summary of changes in holdings, risk, consensus, macro and events.",
    area: "PM Workflow",
    href: "/institutionnel#command-center",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 35,
    titleFr: "Brief matinal du PM",
    titleEn: "PM Morning Brief",
    summaryFr: "Synthèse overnight, positions à surveiller, risques du jour et événements clés.",
    summaryEn: "Summarize overnight moves, watch positions, daily risks and key events.",
    area: "PM Workflow",
    href: "/institutionnel#command-center",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 36,
    titleFr: "Générateur de mémo comité d'investissement",
    titleEn: "Investment Committee Memo Generator",
    summaryFr: "Standardise thèse, valorisation, scénarios, risques, catalyseurs et sources.",
    summaryEn: "Standardize thesis, valuation, scenarios, risks, catalysts and sources.",
    area: "PM Workflow",
    href: "/institutionnel/comite",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 37,
    titleFr: "Workflow comité d'investissement",
    titleEn: "Investment Committee Workflow",
    summaryFr: "Flux analyste → PM → risque → décision → suivi de thèse.",
    summaryEn: "Workflow from analyst to PM to risk to decision and thesis monitoring.",
    area: "PM Workflow",
    href: "/institutionnel/comite",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 38,
    titleFr: "Piste d'audit des décisions",
    titleEn: "Decision Audit Trail",
    summaryFr: "Conserve qui a décidé quoi, quand, pourquoi et avec quelles données.",
    summaryEn: "Record who decided what, when, why and with which data.",
    area: "Data & Governance",
    href: "/institutionnel/gouvernance",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 39,
    titleFr: "Gouvernance des modèles",
    titleEn: "Model Governance",
    summaryFr: "Versionne modèles, hypothèses, calculs et sorties utilisées dans une décision.",
    summaryEn: "Version models, assumptions, calculations and outputs used in decisions.",
    area: "Data & Governance",
    href: "/institutionnel/gouvernance",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 40,
    titleFr: "Contrôle risque pré-transaction",
    titleEn: "Pre-Trade Risk Check",
    summaryFr: "Montre l'impact hypothétique d'une transaction sur concentration, facteurs et liquidité.",
    summaryEn: "Show hypothetical trade impact on concentration, factors and liquidity.",
    area: "Construction & Trading",
    href: "/institutionnel/construction",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 41,
    titleFr: "Moteur de mandat et contraintes",
    titleEn: "Mandate & Constraint Engine",
    summaryFr: "Encode limites de concentration, cash, secteurs, liquidité et autres règles internes.",
    summaryEn: "Encode concentration, cash, sector, liquidity and internal mandate limits.",
    area: "Construction & Trading",
    href: "/institutionnel/construction",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 42,
    titleFr: "Couche de preuve conformité",
    titleEn: "Compliance Evidence Layer",
    summaryFr: "Conserve les éléments expliquant pourquoi un signal ou une alerte a été produit.",
    summaryEn: "Retain evidence explaining why a signal or alert was produced.",
    area: "Data & Governance",
    href: "/institutionnel/gouvernance",
    stage: "roadmap" as InstitutionalCapabilityStage,
  },
  {
    id: 43,
    titleFr: "Intelligence portefeuille client",
    titleEn: "Client Portfolio Intelligence",
    summaryFr: "Relie objectifs client, portefeuille, liquidité, fiscalité et risque.",
    summaryEn: "Connect client goals, portfolio, liquidity, tax context and risk.",
    area: "Wealth & Client",
    href: "/assistant",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 44,
    titleFr: "Pont ménage-portefeuille",
    titleEn: "Household-to-Portfolio Bridge",
    summaryFr: "Relie Anatole Conseil au portefeuille pour vérifier cohérence horizon, liquidité et objectifs.",
    summaryEn: "Connect Anatole Advisor to portfolio context for horizon, liquidity and goal consistency.",
    area: "Wealth & Client",
    href: "/assistant",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 45,
    titleFr: "Tableau de bord du conseiller",
    titleEn: "Advisor Book Dashboard",
    summaryFr: "Vue multi-clients avec événements, échéances, changements et dossiers à revoir.",
    summaryEn: "Multi-client view with events, deadlines, changes and accounts to review.",
    area: "Wealth & Client",
    stage: "roadmap" as InstitutionalCapabilityStage,
  },
  {
    id: 46,
    titleFr: "Préparation de la prochaine revue",
    titleEn: "Next Review Intelligence",
    summaryFr: "Prépare automatiquement changements, progrès objectifs, contributions et questions.",
    summaryEn: "Prepare changes, goal progress, contributions and questions for the next review.",
    area: "Wealth & Client",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 47,
    titleFr: "Mode explication client",
    titleEn: "Client Explanation Mode",
    summaryFr: "Traduit l'analyse institutionnelle en explications simples et traçables pour le client.",
    summaryEn: "Translate institutional analysis into simple, traceable client explanations.",
    area: "Wealth & Client",
    href: "/assistant",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 48,
    titleFr: "Rapports personnalisés",
    titleEn: "Personalized Reporting",
    summaryFr: "Produit des vues institutionnelles ou pédagogiques à partir des mêmes données.",
    summaryEn: "Produce institutional or educational views from the same data.",
    area: "Wealth & Client",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 49,
    titleFr: "Laboratoire de proposition de portefeuille",
    titleEn: "Portfolio Proposal Lab",
    summaryFr: "Compare portefeuille actuel et proposition sur risque, coût, diversification et liquidité.",
    summaryEn: "Compare current and proposed portfolios across risk, cost, diversification and liquidity.",
    area: "Wealth & Client",
    href: "/comparateur",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 50,
    titleFr: "Analyse portefeuille sensible à la fiscalité",
    titleEn: "Tax-Aware Portfolio Analytics",
    summaryFr: "Suit gains/pertes latents, lots fiscaux et impact estimatif selon juridiction.",
    summaryEn: "Track unrealized gains/losses, tax lots and estimated jurisdiction-specific impact.",
    area: "Wealth & Client",
    stage: "roadmap" as InstitutionalCapabilityStage,
  },
  {
    id: 51,
    titleFr: "Vue multi-gestionnaires",
    titleEn: "Multi-Manager View",
    summaryFr: "Analyse chevauchements, facteurs et concentrations entre plusieurs mandats.",
    summaryEn: "Analyze overlaps, factors and concentration across multiple managers.",
    area: "Funds & Multi-Asset",
    href: "/institutionnel/multi-actifs",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 52,
    titleFr: "X-Ray fonds de fonds",
    titleEn: "Fund-of-Funds X-Ray",
    summaryFr: "Traverse ETF et fonds pour révéler les expositions finales sous-jacentes.",
    summaryEn: "Look through ETFs and funds to reveal underlying exposures.",
    area: "Funds & Multi-Asset",
    href: "/institutionnel/multi-actifs",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 53,
    titleFr: "Intelligence ETF institutionnelle",
    titleEn: "Institutional ETF Intelligence",
    summaryFr: "Suit composition, spread, tracking, liquidité et overlap institutionnel.",
    summaryEn: "Track composition, spreads, tracking, liquidity and institutional overlap.",
    area: "Funds & Multi-Asset",
    href: "/institutionnel/multi-actifs",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 54,
    titleFr: "Atelier revenu fixe",
    titleEn: "Fixed Income Workbench",
    summaryFr: "Courbe de taux, duration, convexité, spread, maturités et scénarios de taux.",
    summaryEn: "Yield curve, duration, convexity, spreads, maturities and rate scenarios.",
    area: "Funds & Multi-Asset",
    href: "/institutionnel/multi-actifs",
    stage: "roadmap" as InstitutionalCapabilityStage,
  },
  {
    id: 55,
    titleFr: "Intelligence crédit",
    titleEn: "Credit Intelligence",
    summaryFr: "Analyse maturités, couverture, refinancement, spreads et exposition aux taux.",
    summaryEn: "Analyze maturities, coverage, refinancing, spreads and rate exposure.",
    area: "Funds & Multi-Asset",
    href: "/institutionnel/multi-actifs",
    stage: "roadmap" as InstitutionalCapabilityStage,
  },
  {
    id: 56,
    titleFr: "Couche risque options",
    titleEn: "Options Risk Layer",
    summaryFr: "Greeks, volatilité implicite, skew, expirations et scénarios.",
    summaryEn: "Greeks, implied volatility, skew, expiries and scenarios.",
    area: "Funds & Multi-Asset",
    href: "/institutionnel/multi-actifs",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 57,
    titleFr: "Analyse overlay devises",
    titleEn: "FX Overlay Analytics",
    summaryFr: "Mesure exposition devise et impact de couvertures hypothétiques.",
    summaryEn: "Measure currency exposure and hypothetical hedge impact.",
    area: "Funds & Multi-Asset",
    href: "/institutionnel/multi-actifs",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 58,
    titleFr: "Graphe d'exposition aux matières premières",
    titleEn: "Commodity Exposure Graph",
    summaryFr: "Relie producteurs, consommateurs et titres sensibles aux matières premières.",
    summaryEn: "Connect producers, consumers and securities sensitive to commodities.",
    area: "Funds & Multi-Asset",
    href: "/institutionnel/multi-actifs",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 59,
    titleFr: "Intelligence actifs réels",
    titleEn: "Real Assets Intelligence",
    summaryFr: "Intègre infrastructure, immobilier, énergie et ressources au même moteur de risque.",
    summaryEn: "Bring infrastructure, real estate, energy and resources into one risk engine.",
    area: "Funds & Multi-Asset",
    href: "/institutionnel/multi-actifs",
    stage: "foundation" as InstitutionalCapabilityStage,
  },
  {
    id: 60,
    titleFr: "API institutionnelle",
    titleEn: "Institutional API",
    summaryFr: "Expose analytics portefeuille, risque, qualité données, signaux et scénarios.",
    summaryEn: "Expose portfolio analytics, risk, data quality, signals and scenarios via API.",
    area: "Enterprise Platform",
    stage: "roadmap" as InstitutionalCapabilityStage,
  },
  {
    id: 61,
    titleFr: "Intégration Snowflake / Databricks / S3",
    titleEn: "Snowflake / Databricks / S3 Integration",
    summaryFr: "Lit les données institutionnelles là où elles résident déjà.",
    summaryEn: "Read institutional data where it already lives.",
    area: "Enterprise Platform",
    stage: "roadmap" as InstitutionalCapabilityStage,
  },
  {
    id: 62,
    titleFr: "Intégrations OMS / PMS",
    titleEn: "OMS / PMS Integrations",
    summaryFr: "Connecteurs vers systèmes de gestion d'ordres et portefeuilles institutionnels.",
    summaryEn: "Connect to institutional order and portfolio management systems.",
    area: "Enterprise Platform",
    stage: "roadmap" as InstitutionalCapabilityStage,
  },
  {
    id: 63,
    titleFr: "Intégration CRM",
    titleEn: "CRM Integration",
    summaryFr: "Relie Anatole aux workflows CRM des équipes de gestion de patrimoine.",
    summaryEn: "Connect Anatole with wealth-management CRM workflows.",
    area: "Enterprise Platform",
    stage: "roadmap" as InstitutionalCapabilityStage,
  },
  {
    id: 64,
    titleFr: "Intégrations recherche",
    titleEn: "Research Integrations",
    summaryFr: "Connecte SEDAR+, EDGAR, TMX, transcripts et sources propriétaires autorisées.",
    summaryEn: "Connect SEDAR+, EDGAR, TMX, transcripts and authorized proprietary research sources.",
    area: "Enterprise Platform",
    href: "/focus/RY",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
  {
    id: 65,
    titleFr: "SSO entreprise + RBAC",
    titleEn: "Enterprise SSO + RBAC",
    summaryFr: "Authentification entreprise, rôles, groupes et permissions fines.",
    summaryEn: "Enterprise authentication, roles, groups and fine-grained permissions.",
    area: "Enterprise Platform",
    stage: "roadmap" as InstitutionalCapabilityStage,
  },
  {
    id: 66,
    titleFr: "Résidence et chiffrement des données",
    titleEn: "Data Residency & Encryption",
    summaryFr: "Régions de données, chiffrement, politiques de conservation et clés client à terme.",
    summaryEn: "Data regions, encryption, retention policies and customer-managed keys over time.",
    area: "Enterprise Platform",
    stage: "roadmap" as InstitutionalCapabilityStage,
  },
  {
    id: 67,
    titleFr: "Journaux d'audit complets",
    titleEn: "Complete Audit Logs",
    summaryFr: "Trace accès, modifications, exports et actions sensibles.",
    summaryEn: "Track access, changes, exports and sensitive actions.",
    area: "Enterprise Platform",
    stage: "roadmap" as InstitutionalCapabilityStage,
  },
  {
    id: 68,
    titleFr: "Coffre de recherche privé",
    titleEn: "Private Research Vault",
    summaryFr: "Isole strictement la recherche interne entre organisations et équipes.",
    summaryEn: "Strictly isolate internal research between organizations and teams.",
    area: "Enterprise Platform",
    stage: "roadmap" as InstitutionalCapabilityStage,
  },
  {
    id: 69,
    titleFr: "IA privée / contexte institutionnel",
    titleEn: "Private AI / Institutional Context",
    summaryFr: "Utilise politiques, modèles et recherche internes dans un contexte privé par tenant.",
    summaryEn: "Use internal policies, models and research in a tenant-private context.",
    area: "Enterprise Platform",
    stage: "roadmap" as InstitutionalCapabilityStage,
  },
  {
    id: 70,
    titleFr: "Explicabilité institutionnelle",
    titleEn: "Institutional Explainability",
    summaryFr: "Explique conclusions, sources, hypothèses, transformations et données manquantes.",
    summaryEn: "Explain conclusions, sources, assumptions, transformations and missing data.",
    area: "Data & Governance",
    href: "/institutionnel/gouvernance",
    stage: "bridge" as InstitutionalCapabilityStage,
  },
];

export const INSTITUTIONAL_AREAS = [
  "Portfolio & Risk",
  "Macro & Regimes",
  "Research & Thesis",
  "Data & Governance",
  "Construction & Trading",
  "PM Workflow",
  "Wealth & Client",
  "Funds & Multi-Asset",
  "Enterprise Platform",
] as const;
