import { StyleSheet, Text, View } from "react-native";

import { Card, QueryState, uiStyles } from "@/src/components/ui";
import type { FundamentalSnapshot } from "@/src/lib/api/types";
import { useLocale } from "@/src/lib/i18n";
import { colors, spacing, typography } from "@/src/theme/tokens";
import { moneyOrNd, percentOrNd, valueOrNd } from "./format";

export function MobileFocusAnalysts({ snapshot, loading, error, onRetry }: { snapshot?: FundamentalSnapshot; loading: boolean; error: Error | null; onRetry: () => void }) {
  const { language, pick } = useLocale();
  const a = snapshot?.analysts;
  const currency = snapshot?.currency ?? "CAD";
  return <View style={styles.stack} testID="focus-analysts-section"><QueryState error={!snapshot ? error : null} loading={loading} onRetry={onRetry} />{snapshot && a ? <>
    <Card title={pick("Consensus", "Consensus")}><Text style={styles.recommendation}>{a.recommendation_key?.replaceAll("_", " ").toUpperCase() ?? "N/D"}</Text><View style={uiStyles.row}><Text style={uiStyles.label}>{pick("Nombre d’analystes", "Analyst count")}</Text><Text style={styles.value}>{valueOrNd(a.analyst_count, 0, language)}</Text></View><View style={uiStyles.row}><Text style={uiStyles.label}>{pick("Cible basse", "Target low")}</Text><Text style={styles.value}>{moneyOrNd(a.target_low, currency, false, language)}</Text></View><View style={uiStyles.row}><Text style={uiStyles.label}>{pick("Cible moyenne", "Target mean")}</Text><Text style={styles.value}>{moneyOrNd(a.target_mean, currency, false, language)}</Text></View><View style={uiStyles.row}><Text style={uiStyles.label}>{pick("Cible médiane", "Target median")}</Text><Text style={styles.value}>{moneyOrNd(a.target_median, currency, false, language)}</Text></View><View style={uiStyles.row}><Text style={uiStyles.label}>{pick("Cible haute", "Target high")}</Text><Text style={styles.value}>{moneyOrNd(a.target_high, currency, false, language)}</Text></View><View style={uiStyles.row}><Text style={uiStyles.label}>{pick("Potentiel vers moyenne", "Upside to mean")}</Text><Text style={styles.value}>{percentOrNd(a.upside_to_mean_percent, language)}</Text></View></Card>
    <Card title={pick("Répartition", "Distribution")}><View style={styles.ratings}>{[["Strong Buy", a.strong_buy], ["Buy", a.buy], ["Hold", a.hold], ["Sell", a.sell], ["Strong Sell", a.strong_sell]].map(([label, value]) => <View key={String(label)} style={styles.rating}><Text style={styles.ratingValue}>{valueOrNd(value as number | null, 0, language)}</Text><Text style={styles.ratingLabel}>{label}</Text></View>)}</View></Card>
    <Card title={pick("Historique des résultats", "Earnings history")}>{snapshot.earnings_history.length ? snapshot.earnings_history.map((row) => <View key={row.period} style={styles.block}><Text style={styles.blockTitle}>{row.period}</Text><Text style={styles.line}>{pick("Réel", "Actual")}: {valueOrNd(row.actual, 2, language)} · {pick("Estimé", "Estimate")}: {valueOrNd(row.estimate, 2, language)} · {pick("Surprise", "Surprise")}: {percentOrNd(row.surprise_percent, language)}</Text></View>) : <Text style={styles.line}>N/D</Text>}</Card>
    <Card title={pick("Estimations", "Estimates")}>{snapshot.earnings_estimates.length ? snapshot.earnings_estimates.map((row) => <View key={row.period} style={styles.block}><Text style={styles.blockTitle}>{row.period} {row.end_date ?? ""}</Text><Text style={styles.line}>EPS {valueOrNd(row.eps_low, 2, language)} — {valueOrNd(row.eps_average, 2, language)} — {valueOrNd(row.eps_high, 2, language)} · n={valueOrNd(row.eps_analyst_count, 0, language)}</Text><Text style={styles.line}>{pick("Revenus", "Revenue")} {moneyOrNd(row.revenue_low, currency, true, language)} — {moneyOrNd(row.revenue_average, currency, true, language)} — {moneyOrNd(row.revenue_high, currency, true, language)} · n={valueOrNd(row.revenue_analyst_count, 0, language)}</Text></View>) : <Text style={styles.line}>N/D</Text>}</Card>
    <Card title={pick("Événements", "Events")}><View style={uiStyles.row}><Text style={uiStyles.label}>{pick("Résultats", "Earnings")}</Text><Text style={styles.value}>{snapshot.events.earnings_dates[0] ? new Date(snapshot.events.earnings_dates[0]).toLocaleDateString(language === "fr" ? "fr-CA" : "en-CA") : "N/D"}</Text></View><View style={uiStyles.row}><Text style={uiStyles.label}>Ex-dividende</Text><Text style={styles.value}>{snapshot.events.ex_dividend_date ? new Date(snapshot.events.ex_dividend_date).toLocaleDateString(language === "fr" ? "fr-CA" : "en-CA") : "N/D"}</Text></View><View style={uiStyles.row}><Text style={uiStyles.label}>{pick("Dividende", "Dividend")}</Text><Text style={styles.value}>{snapshot.events.dividend_date ? new Date(snapshot.events.dividend_date).toLocaleDateString(language === "fr" ? "fr-CA" : "en-CA") : "N/D"}</Text></View></Card>
  </> : null}</View>;
}
const styles = StyleSheet.create({ stack: { gap: spacing.md }, recommendation: { ...typography.title, color: colors.primary }, value: { ...typography.body, color: colors.text, fontWeight: "700", textAlign: "right" }, ratings: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, rating: { flexGrow: 1, minWidth: "28%", padding: spacing.sm, borderWidth: 1, borderColor: colors.border, alignItems: "center" }, ratingValue: { ...typography.section, color: colors.text }, ratingLabel: { ...typography.caption, color: colors.textMuted }, block: { gap: spacing.xs, paddingVertical: spacing.sm, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, blockTitle: { ...typography.label, color: colors.text }, line: { ...typography.caption, color: colors.textMuted } });
