import { useQuery } from "@tanstack/react-query";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { Button, Card, Field, QueryState } from "@/src/components/ui";
import { marketApi } from "@/src/lib/api/market";
import type { CompanyNetworkNode, CompanyRelationship } from "@/src/lib/api/types";
import { useLocale } from "@/src/lib/i18n";
import { colors, radius, spacing, typography } from "@/src/theme/tokens";

type EcosystemTab = "chain" | "network" | "evidence";
function NodeCard({ node, central = false }: { node: CompanyNetworkNode; central?: boolean }) {
  const { pick } = useLocale();
  return <Pressable disabled={!node.ticker} onPress={() => node.ticker && router.push({ pathname: "/focus/[ticker]", params: { ticker: node.ticker.replace(/\.TO$/i, "") } })} style={[styles.node, central && styles.central]}><Text style={styles.nodeName}>{node.name}</Text><Text style={styles.nodeMeta}>{node.ticker ?? node.node_type} · {node.sector ?? pick("secteur N/D", "sector N/A")}</Text></Pressable>;
}
function RelationCard({ relationship, nodes }: { relationship: CompanyRelationship; nodes: Map<string, CompanyNetworkNode> }) {
  const { pick } = useLocale();
  const source = nodes.get(relationship.source_node_id); const target = nodes.get(relationship.target_node_id);
  return <View style={styles.relation}><Text style={styles.relationTitle}>{source?.name ?? relationship.source_node_id} → {target?.name ?? relationship.target_node_id}</Text><Text style={styles.relationMeta}>{relationship.relationship_type.replaceAll("_", " ")} · {relationship.confidence} · {relationship.materiality}</Text><Text style={styles.relationMeta}>{pick("Sources", "Sources")}: {relationship.source_count} · {relationship.last_verified_at ? new Date(relationship.last_verified_at).toLocaleDateString() : "N/D"}</Text>{relationship.evidence[0] ? <Text numberOfLines={3} style={styles.excerpt}>{relationship.evidence[0].excerpt}</Text> : null}</View>;
}

export function MobileFocusEcosystem({ ticker }: { ticker: string }) {
  const { language, pick } = useLocale();
  const [tab, setTab] = useState<EcosystemTab>("chain"); const [depth, setDepth] = useState<1 | 2>(1); const [target, setTarget] = useState("");
  const network = useQuery({ queryKey: ["company-network", ticker, depth], queryFn: ({ signal }) => marketApi.companyNetwork(ticker, depth, signal), staleTime: 15 * 60_000, refetchInterval: (query) => query.state.data?.coverage.build_status === "building" ? (query.state.data.coverage.retry_after_seconds ?? 5) * 1000 : false });
  const evidence = useQuery({ queryKey: ["company-network-evidence", ticker], queryFn: ({ signal }) => marketApi.companyNetworkEvidence(ticker, signal), enabled: tab === "evidence", staleTime: 15 * 60_000 });
  const path = useQuery({ queryKey: ["company-network-path", ticker, target], queryFn: ({ signal }) => marketApi.companyNetworkPath(ticker, target, signal), enabled: false });
  const nodeMap = useMemo(() => new Map(network.data?.nodes.map((node) => [node.id, node]) ?? []), [network.data]);
  const related = (types: CompanyRelationship["relationship_type"][]) => network.data?.relationships.filter((relation) => types.includes(relation.relationship_type)).map((relation) => nodeMap.get(relation.source_node_id === network.data.center.id ? relation.target_node_id : relation.source_node_id)).filter((node): node is CompanyNetworkNode => Boolean(node)) ?? [];
  const suppliers = related(["supplier", "distributor"]); const customers = related(["customer", "major_contract"]); const partners = related(["strategic_partner", "joint_venture", "parent", "subsidiary"]); const markets = network.data?.nodes.filter((node) => node.node_type === "end_market" || node.node_type === "commodity") ?? [];
  const message = network.data?.coverage[language === "fr" ? "message_fr" : "message_en"];
  return <View style={styles.stack} testID="focus-ecosystem-section">
    <View style={styles.tabs}>{(["chain", "network", "evidence"] as const).map((value) => <Pressable key={value} onPress={() => setTab(value)} style={[styles.tab, tab === value && styles.active]}><Text style={styles.tabText}>{value === "chain" ? pick("Chaîne", "Chain") : value === "network" ? pick("Réseau", "Network") : pick("Preuves", "Evidence")}</Text></Pressable>)}</View>
    <QueryState error={!network.data ? network.error : null} loading={network.isLoading} onRetry={() => void network.refetch()} />
    {network.data ? <><Card title={`${pick("État", "Status")}: ${network.data.coverage.build_status}`}><Text style={styles.copy}>{message ?? `${network.data.relationships.length} ${pick("relations publiques", "public relationships")} · ${network.data.coverage.verified_relationships} ${pick("vérifiées", "verified")}`}</Text>{network.data.stale ? <Text style={styles.warning}>{pick("Instantané antérieur affiché pendant l’actualisation.", "Previous snapshot shown during refresh.")}</Text> : null}</Card>
      {tab === "chain" ? <Card title={pick("Chaîne de valeur", "Value chain")}><Text style={styles.label}>{pick("Fournisseurs", "Suppliers")}</Text>{suppliers.length ? suppliers.map((node) => <NodeCard key={`s-${node.id}`} node={node} />) : <Text style={styles.empty}>—</Text>}<Text style={styles.arrow}>↓</Text><NodeCard central node={network.data.center} /><Text style={styles.arrow}>↓</Text><Text style={styles.label}>{pick("Clients / acheteurs", "Customers / buyers")}</Text>{customers.length ? customers.map((node) => <NodeCard key={`c-${node.id}`} node={node} />) : <Text style={styles.empty}>—</Text>}<Text style={styles.arrow}>↓</Text><Text style={styles.label}>{pick("Marchés finaux", "End markets")}</Text>{markets.length ? markets.map((node) => <NodeCard key={`m-${node.id}`} node={node} />) : <Text style={styles.empty}>—</Text>}<Text style={styles.label}>{pick("Partenaires / filiales", "Partners / subsidiaries")}</Text>{partners.length ? partners.map((node) => <NodeCard key={`p-${node.id}`} node={node} />) : <Text style={styles.empty}>—</Text>}</Card> : null}
      {tab === "network" ? <><Card action={<Pressable onPress={() => setDepth(depth === 1 ? 2 : 1)} style={styles.depth}><Text style={styles.tabText}>{pick("Profondeur", "Depth")} {depth}</Text></Pressable>} title={pick("Réseau vérifié", "Verified network")}>{network.data.relationships.length ? network.data.relationships.map((relation) => <RelationCard key={relation.id} nodes={nodeMap} relationship={relation} />) : <Text style={styles.empty}>{pick("Aucune relation vérifiable trouvée.", "No verifiable relationship found.")}</Text>}</Card><Card title={pick("Trouver le lien", "Find relationship")}><Field autoCapitalize="characters" label={pick("Entreprise cible", "Target company")} onChangeText={setTarget} placeholder="SHOP, CNQ…" value={target} /><Button disabled={!target.trim() || path.isFetching} label={pick("Trouver le lien", "Find path")} onPress={() => void path.refetch()} variant="secondary" />{path.data ? <Text style={styles.copy}>{path.data.found ? path.data.nodes.map((node) => node.ticker ?? node.name).join(" → ") : (language === "fr" ? path.data.message_fr : path.data.message_en) ?? pick("Aucun chemin vérifiable.", "No verifiable path.")}</Text> : null}</Card></> : null}
      {tab === "evidence" ? <Card title={pick("Preuves traçables", "Traceable evidence")}><QueryState error={!evidence.data ? evidence.error : null} loading={evidence.isLoading} onRetry={() => void evidence.refetch()} />{evidence.data?.groups.flatMap((group) => group.evidence.map((item) => <View key={item.id} style={styles.relation}><Text style={styles.relationTitle}>{item.title}</Text><Text style={styles.relationMeta}>{item.issuer} · {item.source_type}</Text><Text style={styles.excerpt}>{item.excerpt}</Text></View>))}</Card> : null}
    </> : null}
  </View>;
}
const styles = StyleSheet.create({ stack: { gap: spacing.md }, tabs: { flexDirection: "row", gap: spacing.xs }, tab: { flex: 1, minHeight: 44, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm }, active: { borderColor: colors.primary, backgroundColor: "rgba(44,156,255,.2)" }, tabText: { ...typography.label, color: colors.text }, copy: { ...typography.body, color: colors.textMuted }, warning: { ...typography.caption, color: colors.warning }, label: { ...typography.label, color: colors.primary, textTransform: "uppercase", marginTop: spacing.sm }, node: { minHeight: 60, justifyContent: "center", padding: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surfaceRaised }, central: { borderColor: colors.primary, backgroundColor: "rgba(44,156,255,.18)" }, nodeName: { ...typography.body, color: colors.text, fontWeight: "800" }, nodeMeta: { ...typography.caption, color: colors.textMuted }, arrow: { fontSize: 24, color: colors.primary, textAlign: "center" }, empty: { ...typography.body, color: colors.textSubtle }, relation: { gap: spacing.xs, paddingVertical: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, relationTitle: { ...typography.body, color: colors.text, fontWeight: "700" }, relationMeta: { ...typography.caption, color: colors.primary }, excerpt: { ...typography.caption, color: colors.textMuted }, depth: { minHeight: 44, justifyContent: "center", paddingHorizontal: spacing.sm, borderWidth: 1, borderColor: colors.borderStrong, borderRadius: radius.sm } });
