import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { useLocale } from "@/src/lib/i18n";
import { colors, radius, spacing, typography } from "@/src/theme/tokens";
import type { CalendarFiltersState, CalendarImportanceFilter, CalendarKindFilter, CalendarRange, CalendarRegionFilter } from "./model";

function Chip({ label, selected, onPress, testID }: { label: string; selected: boolean; onPress: () => void; testID?: string }) {
  return <Pressable accessibilityRole="button" accessibilityState={{ selected }} onPress={onPress} style={[styles.chip, selected && styles.active]} testID={testID}><Text style={[styles.text, selected && styles.activeText]}>{label}</Text></Pressable>;
}

export function CalendarFilters({ filters, categories, sectors, hasPersonal, preferredRegions = [], onChange }: { filters: CalendarFiltersState; categories: readonly string[]; sectors: readonly string[]; hasPersonal: boolean; preferredRegions?: readonly string[]; onChange: (filters: CalendarFiltersState) => void }) {
  const { pick } = useLocale();
  const ranges: { id: CalendarRange; label: string }[] = [{ id: "today", label: pick("Aujourd’hui", "Today") }, { id: "7d", label: pick("7 jours", "7 days") }, { id: "30d", label: pick("30 jours", "30 days") }];
  const kinds: { id: CalendarKindFilter; label: string }[] = [{ id: "all", label: pick("Tous", "All") }, { id: "economic", label: pick("Économie", "Economy") }, { id: "earnings", label: pick("Résultats", "Earnings") }];
  const importance: { id: CalendarImportanceFilter; label: string }[] = [{ id: "all", label: pick("Toutes importances", "All importance") }, { id: "high", label: pick("Élevée", "High") }, { id: "medium", label: pick("Moyenne", "Medium") }, { id: "low", label: pick("Faible", "Low") }];
  const regions: { id: CalendarRegionFilter; label: string }[] = [{ id: "all", label: pick("Toutes régions", "All regions") }, { id: "CA", label: "Canada" }, { id: "QC", label: "QC" }, { id: "ON", label: "ON" }, { id: "BC", label: "BC" }, { id: "AB", label: "AB" }, { id: "prairies", label: "Prairies" }, { id: "atlantic", label: pick("Atlantique", "Atlantic") }];
  return <View style={styles.container} testID="calendar-filters">
    <View style={styles.segment}>{ranges.map((item) => <Chip key={item.id} label={item.label} onPress={() => onChange({ ...filters, range: item.id })} selected={filters.range === item.id} testID={`calendar-range-${item.id}`} />)}</View>
    <ScrollView contentContainerStyle={styles.row} horizontal showsHorizontalScrollIndicator={false}>{kinds.map((item) => <Chip key={item.id} label={item.label} onPress={() => onChange({ ...filters, kind: item.id })} selected={filters.kind === item.id} testID={`calendar-kind-${item.id}`} />)}{preferredRegions.length ? <Chip label={pick("Mes régions", "My regions")} onPress={() => onChange({ ...filters, scope: filters.scope === "preferred" ? "all" : "preferred" })} selected={filters.scope === "preferred"} testID="calendar-preferred-regions" /> : null}{hasPersonal ? <Chip label={pick("Mes événements", "My events")} onPress={() => onChange({ ...filters, scope: filters.scope === "personal" ? "all" : "personal" })} selected={filters.scope === "personal"} testID="calendar-personal" /> : null}</ScrollView>
    <ScrollView contentContainerStyle={styles.row} horizontal showsHorizontalScrollIndicator={false}>{importance.map((item) => <Chip key={item.id} label={item.label} onPress={() => onChange({ ...filters, importance: item.id })} selected={filters.importance === item.id} testID={`calendar-importance-${item.id}`} />)}</ScrollView>
    <ScrollView contentContainerStyle={styles.row} horizontal showsHorizontalScrollIndicator={false}>{regions.map((item) => <Chip key={item.id} label={item.label} onPress={() => onChange({ ...filters, region: item.id })} selected={filters.region === item.id} testID={`calendar-region-${item.id}`} />)}</ScrollView>
    <ScrollView contentContainerStyle={styles.row} horizontal showsHorizontalScrollIndicator={false}><Chip label={pick("Toutes catégories", "All categories")} onPress={() => onChange({ ...filters, category: "all" })} selected={filters.category === "all"} />{categories.map((category) => <Chip key={category} label={category} onPress={() => onChange({ ...filters, category })} selected={filters.category === category} />)}</ScrollView>
    {sectors.length ? <ScrollView contentContainerStyle={styles.row} horizontal showsHorizontalScrollIndicator={false}><Chip label={pick("Tous secteurs", "All sectors")} onPress={() => onChange({ ...filters, sector: "all" })} selected={filters.sector === "all"} />{sectors.map((sector) => <Chip key={sector} label={sector} onPress={() => onChange({ ...filters, sector })} selected={filters.sector === sector} />)}</ScrollView> : null}
    {filters.ticker ? <TextInput accessibilityLabel={pick("Filtre symbole", "Ticker filter")} autoCapitalize="characters" onChangeText={(ticker) => onChange({ ...filters, ticker })} style={styles.input} value={filters.ticker} /> : null}
  </View>;
}

const styles = StyleSheet.create({ container: { gap: spacing.sm }, segment: { flexDirection: "row", gap: spacing.xs }, row: { gap: spacing.xs, paddingRight: spacing.lg }, chip: { minHeight: 44, justifyContent: "center", paddingHorizontal: spacing.md, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceRaised }, active: { borderColor: colors.primary, backgroundColor: "rgba(44,156,255,.18)" }, text: { ...typography.caption, color: colors.textMuted, fontWeight: "700" }, activeText: { color: colors.text }, input: { minHeight: 48, paddingHorizontal: spacing.md, color: colors.text, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceRaised } });
