import { useQuery } from "@tanstack/react-query";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import Svg, { Polyline } from "react-native-svg";
import { Button, Card, Field, QueryState, Screen, ScreenHeader } from "@/src/components/ui";
import { intelligenceApi } from "@/src/lib/api/intelligence";
import type { ComparisonRange, ComparisonSnapshot } from "@/src/lib/api/types";
import { useLocale } from "@/src/lib/i18n";
import { anatoleRoutes } from "@/src/lib/routes";
import { useMobileAccount } from "@/src/providers/MobileAccountProvider";
import { colors, radius, spacing, typography } from "@/src/theme/tokens";
import { comparisonDatesAreAligned, comparisonValue, normalizeComparisonSymbols } from "./model";

const ranges: ComparisonRange[] = ["1mo", "3mo", "6mo", "ytd", "1y"];
const palette = [colors.primary, colors.positive, colors.warning, "#b27cff", colors.negative];
function PerformanceChart({ snapshot }: { snapshot: ComparisonSnapshot }) {
  const points = snapshot.series.flatMap((item) => item.points); if (!points.length || !comparisonDatesAreAligned(snapshot)) return <Text style={styles.note}>N/D</Text>;
  const minTime = Math.min(...points.map((item) => item.time)); const maxTime = Math.max(...points.map((item) => item.time)); const min = Math.min(...points.map((item) => item.value)); const max = Math.max(...points.map((item) => item.value));
  return <View accessible accessibilityLabel="Performance base 100" style={styles.chart}><Svg height={180} viewBox="0 0 340 180" width="100%">{snapshot.series.map((series, index) => <Polyline fill="none" key={series.symbol} points={series.points.map((item) => `${10 + (item.time - minTime) / Math.max(1, maxTime - minTime) * 320},${10 + (max - item.value) / Math.max(1, max - min) * 160}`).join(" ")} stroke={palette[index]} strokeWidth={2} />)}</Svg></View>;
}
export function ComparatorScreen() {
  const params = useLocalSearchParams<{ symbols?: string }>(); const { workspace, saveWorkspace } = useMobileAccount(); const { pick } = useLocale(); const initial = normalizeComparisonSymbols(String(params.symbols ?? "").split(",").filter(Boolean).length ? String(params.symbols).split(",") : workspace.data.comparator_symbols); const [symbols, setSymbols] = useState(initial); const [entry, setEntry] = useState(""); const [range, setRange] = useState<ComparisonRange>("1y");
  const query = useQuery({ queryKey: ["comparison", symbols, range], queryFn: ({ signal }) => intelligenceApi.compare(symbols, range, signal), enabled: symbols.length >= 2, staleTime: 5 * 60_000 });
  useEffect(() => { if (symbols.length >= 2) void saveWorkspace({ ...workspace.data, comparator_symbols: symbols }); }, [symbols]); // eslint-disable-line react-hooks/exhaustive-deps
  const add = () => { const next = normalizeComparisonSymbols([...symbols, entry]); setSymbols(next); setEntry(""); };
  return <Screen onRefresh={() => void query.refetch()} refreshing={query.isRefetching} testID="comparator-screen"><ScreenHeader eyebrow="BASE 100" title={pick("Comparateur", "Comparator")} subtitle={pick("Jusqu’à cinq actions ou ETF sur des dates communes, sans remplissage prolongé.", "Up to five stocks or ETFs on shared dates, without prolonged forward-fill.")} /><Card><Field autoCapitalize="characters" label={`${pick("Ajouter", "Add")} · ${symbols.length}/5`} onChangeText={setEntry} onSubmitEditing={add} placeholder="RY, XIU…" value={entry} /><Button disabled={!entry.trim() || symbols.length >= 5} label={pick("Ajouter", "Add")} onPress={add} /><View style={styles.wrap}>{symbols.map((symbol) => <Pressable key={symbol} onPress={() => setSymbols(symbols.filter((item) => item !== symbol))} style={styles.chip}><Text style={styles.chipText}>{symbol} ×</Text></Pressable>)}</View><View style={styles.wrap}>{ranges.map((item) => <Pressable accessibilityState={{ selected: range === item }} key={item} onPress={() => setRange(item)} style={[styles.chip, range === item && styles.active]}><Text style={styles.chipText}>{item.toUpperCase()}</Text></Pressable>)}</View></Card><QueryState error={!query.data ? query.error : null} loading={query.isLoading} onRetry={() => void query.refetch()} />{symbols.length < 2 ? <Card><Text style={styles.note}>{pick("Sélectionnez au moins deux instruments.", "Select at least two instruments.")}</Text></Card> : null}{query.data ? <><Card title={pick("Performance normalisée", "Normalized performance")}><PerformanceChart snapshot={query.data} /></Card><Card title={pick("Mesures", "Metrics")}>{query.data.instruments.map((item) => <Pressable key={item.symbol} onPress={() => router.push(anatoleRoutes.focus(item.symbol))} style={styles.instrument}><Text style={styles.title}>{item.symbol} · {item.name}</Text><Text style={styles.note}>{comparisonValue(item.total_return_percent, "%")} · Vol {comparisonValue(item.volatility_percent, "%")} · Beta {comparisonValue(item.beta)} · Momentum {comparisonValue(item.momentum_20d, "%")} · RSI {comparisonValue(item.rsi_14)} · Score {comparisonValue(item.score)}</Text></Pressable>)}</Card><Card title={pick("Corrélations descriptives", "Descriptive correlations")}>{query.data.correlation.symbols.map((symbol, row) => <Text key={symbol} style={styles.matrix}>{symbol} · {query.data!.correlation.values[row]?.map((value) => comparisonValue(value)).join("  ")}</Text>)}<Text style={styles.note}>{query.data.methodology}</Text></Card></> : null}</Screen>;
}
const styles = StyleSheet.create({ wrap: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs }, chip: { minHeight: 44, justifyContent: "center", paddingHorizontal: spacing.sm, borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm }, active: { borderColor: colors.primary, backgroundColor: "rgba(44,156,255,.2)" }, chipText: { ...typography.label, color: colors.text }, chart: { height: 180, borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm, overflow: "hidden" }, instrument: { minHeight: 64, justifyContent: "center", borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, title: { ...typography.body, color: colors.text, fontWeight: "800" }, note: { ...typography.caption, color: colors.textMuted }, matrix: { ...typography.body, color: colors.text, fontVariant: ["tabular-nums"] } });
