import { useLocalSearchParams } from "expo-router";
import { useRef, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Button, Card, Field, Screen, ScreenHeader } from "@/src/components/ui";
import { workspaceApi } from "@/src/lib/api/workspace";
import type { AssistantResponse } from "@/src/lib/api/types";
import { useLocale } from "@/src/lib/i18n";
import { useMobileAccount } from "@/src/providers/MobileAccountProvider";
import { colors, radius, spacing, typography } from "@/src/theme/tokens";
import { assistantIsGrounded, containsRecommendation, containsUnsupportedCausality } from "./grounding";

const prompts = [["Pourquoi ce titre bouge aujourd’hui ?", "Why is this security moving today?"], ["Que dois-je surveiller sur ce titre ?", "What should I monitor for this security?"], ["Explique-moi le risque de mon portefeuille.", "Explain my portfolio risk."], ["Compare RY et TD.", "Compare RY and TD."], ["Que se passe-t-il sur le marché canadien ?", "What is happening in the Canadian market?"]] as const;
export function AssistantContextScreen() {
  const { symbol } = useLocalSearchParams<{ symbol?: string }>(); const { workspace } = useMobileAccount(); const { pick } = useLocale(); const [message, setMessage] = useState(""); const [response, setResponse] = useState<AssistantResponse | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const controller = useRef<AbortController | null>(null);
  const ask = async () => { if (!message.trim()) return; controller.current?.abort(); controller.current = new AbortController(); setLoading(true); setError(null); try { const next = await workspaceApi.assistant(message, workspace.data.portfolio, symbol, controller.current.signal); if (!assistantIsGrounded(next) || containsUnsupportedCausality(next.answer) || containsRecommendation(next.answer)) throw new Error(pick("Réponse non conforme aux garde-fous.", "Response failed grounding guardrails.")); setResponse(next); } catch (cause) { if (!(cause instanceof Error && cause.name === "AbortError")) setError(cause instanceof Error ? cause.message : pick("Assistant indisponible.", "Assistant unavailable.")); } finally { setLoading(false); } };
  return <Screen testID="assistant-screen"><ScreenHeader eyebrow="EVIDENCE BUNDLE" title={pick("Assistant Anatole", "Anatole Assistant")} subtitle={pick("Réponses contextuelles déterministes fondées uniquement sur les données Anatole sourcées.", "Deterministic contextual answers based only on sourced Anatole data.")} /><View style={styles.prompts}>{prompts.map(([fr, en]) => <Pressable key={fr} onPress={() => setMessage(pick(fr, en))} style={styles.prompt}><Text style={styles.promptText}>{pick(fr, en)}</Text></Pressable>)}</View><Field label={pick("Question", "Question")} multiline onChangeText={setMessage} value={message} /><Button disabled={!message.trim() || loading} label={loading ? pick("Analyse…", "Analyzing…") : pick("Interroger Anatole", "Ask Anatole")} onPress={() => void ask()} />{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}{response ? <Card title={response.title}><Text style={styles.answer}>{response.answer.replaceAll("**", "")}</Text>{response.facts.map((item) => <Text key={item.label} style={styles.fact}>{item.label} · {item.value}</Text>)}<Text style={styles.sourceTitle}>{pick("Sources utilisées", "Sources used")} · {new Date(response.generated_at).toLocaleString()}</Text>{response.sources.length ? response.sources.map((source) => <Text key={`${source.label}-${source.detail}`} style={styles.source}>{source.label} · {source.detail}</Text>) : <Text style={styles.source}>N/D</Text>}<Text style={styles.disclaimer}>{response.disclaimer}</Text></Card> : null}</Screen>;
}
const styles = StyleSheet.create({ prompts: { gap: spacing.xs }, prompt: { minHeight: 44, justifyContent: "center", paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm }, promptText: { ...typography.caption, color: colors.primary }, error: { ...typography.body, color: colors.negative }, answer: { ...typography.body, color: colors.text }, fact: { ...typography.caption, color: colors.textMuted }, sourceTitle: { ...typography.label, color: colors.primary, marginTop: spacing.sm }, source: { ...typography.caption, color: colors.textMuted }, disclaimer: { ...typography.caption, color: colors.textSubtle } });
